# -------------------------------------------------
# Eden framework configuration
# -------------------------------------------------

# SECURITY WARNING: don't run with debug turned on in production!
debug: True

# -------------------------
# Components plugins      |
# -------------------------
components:
  - eden.components.werkzeug
  - eden.components.jinja

# ---------------------
# Database setting    |
# ---------------------
database:
    database: 'postgresql'
    database_hostname: 'localhost'
    database_port: '5432'
    database_name: 'edendev'
    database_username: 'root'
    database_password: 'password'


# ----------------------------
# Components settings        |
# ----------------------------

# Werkzeug route
werkzeug_route:
  - app.my_component.config.config

# Werkzeug middleware
werkzeug_middleware:
  - eden.components.werkzeug.StaticFilesMiddleware
  - eden.components.werkzeug.StaticFilesMiddleware

werkzeug_static: '%base_url%/static'


# Jinja tempalte url
jinja_config: '%base_url%/template'



