# -------------------------------------------------
# Eden framework config
# -------------------------------------------------

# SECURITY WARNING: don't run with debug turned on in production!
debug: True

# ----------------------
# Topical plugins      |
# ----------------------
plugins:
  - eden.plugin.managements
  - eden.core.validators


# ---------------------
# Database setting    |
# ---------------------
database:
    database: 'postgresql'
    database_hostname: 'localhost'
    database_port: '5432'
    database_name: 'edendev'
    database_username: 'root'
    database_password: 'password'



